# Generated by Django 4.0.1 on 2022-01-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.IntegerField(editable=False),
        ),
    ]
